apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cv-app
  labels:
    app: cv-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cv-app
  template:
    metadata:
      labels:
        app: cv-app
    spec:
      containers:
        - name: cv-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
